server:
  port: 8091

# Spring 整合 kafka
spring:
  kafka:
    bootstrap-servers: 132.232.178.235:9092
    # 消息的签收机制：手动签收
    consumer:
      enable-auto-commit: false # 取消自动签收
      auto-offset-reset: earliest # 便宜量 latest 在偏移量无效的情况下，消费者从最新的记录开始读取，启动后的记录  earliest：在偏移量无效的情况下，消费者将从其实位置读取分区记录
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual  # 手动签收
      concurrency: 5 # 线程数目 并行度

