server:
  port: 8090

# Spring 整合 kafka
spring:
  kafka:
    bootstrap-servers: 132.232.178.235:9092
    producer:
      retries: 0 # kafka producer 发送消息失败时一个重试的次数
      batch-size: 16384 # 批量发送数据的配置
      buffer-memory: 33554432 # 设置 kafka生产者内存缓存区的大小（32M）
      # kafka 消息序列化配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # kafka 生产端最重要的选项 确定什么情况算消息发送成功
      # acks = 0 ： 生产者在成功写入消息之前，不会等待任何来自服务器的响应 【消息投递即可不做等待】
      # acks = 1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应
      # acks = -1 ：表示分区leader必须等待消息被成功写入到所有的ISR副本（同步副本）中才认为produce请求成功。这种方案提供最高的消息持久性保证，但是理论上来讲吞吐量最差。
      acks: 1